### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by rd15armas** [bg2bhc/gr-lilacsat#12]
i have got these error: 
[  1%] Building CXX object lib/CMakeFiles/gnuradio-lilacsat.dir/afsk1200_tx_f_impl.cc.o
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc: In member function ‘virtual int gr::lilacsat::afsk1200_tx_f_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:163:69: error: narrowing conversion of ‘254’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  char msg_ptt_on[] = {0xFE, 0xFE, 0x7C, 0xE0, 0x1C, 0x00, 0x01, 0xFD};
                                                                     ^
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:163:69: error: narrowing conversion of ‘254’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:163:69: error: narrowing conversion of ‘224’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:163:69: error: narrowing conversion of ‘253’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:164:70: error: narrowing conversion of ‘254’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  char msg_ptt_off[] = {0xFE, 0xFE, 0x7C, 0xE0, 0x1C, 0x00, 0x00, 0xFD};
                                                                      ^
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:164:70: error: narrowing conversion of ‘254’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:164:70: error: narrowing conversion of ‘224’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/hp/gr-satellites/build/gr-lilacsat/lib/afsk1200_tx_f_impl.cc:164:70: error: narrowing conversion of ‘253’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
lib/CMakeFiles/gnuradio-lilacsat.dir/build.make:398: recipe for target 'lib/CMakeFiles/gnuradio-lilacsat.dir/afsk1200_tx_f_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-lilacsat.dir/afsk1200_tx_f_impl.cc.o] Error 1
CMakeFiles/Makefile2:137: recipe for target 'lib/CMakeFiles/gnuradio-lilacsat.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-lilacsat.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by liiyuanshuai** [comment]
have you fixed the error?

**Comment by rd15armas** [comment]
Yes. I have fixed.

**Comment by liiyuanshuai** [comment]
can you remember how you fixed it? i am troubled.

**Comment by liiyuanshuai** [comment]
can you remember how you fixed it? i am troubled.

**Comment by liiyuanshuai** [comment]
can you remember how you fixed it? i am troubled.

**Comment by rd15armas** [comment]
if you give your email then i will send it.

Because I didn't send files to this email address.

Mail delivery failed: returning message to sender
