### ISSUE TITLE
Attribute error happens when I want to make a new block by OOT module in gnuradio 3.7.13.4

### ISSUE THREAD

**Issue by shiwang-Xing** [bg2bhc/gr-lilacsat#25]
Dear guys,

I want to learn how to generate a new block, I have alreay follow the gr-tutorial from the guide book from Gnuradio Website.  I want to change the AFSK date rate into 9600bps, firstly I copied your codes into the OOT module. I have change the .cpp, .h, and the .xml files in the floder. It can be built and install well. But when I use it to run, Something happened like the followings. I have used the sudo make install and sudo ldconfig. Besides, I can run your softwares very well.

```

File "/home/wang/study-gnuradio/graduate/top_block.py", line 95, in init
self.shiwang_afsk_9600_0 = shiwang.afsk_9600(False, 1, 1)
AttributeError: 'module' object has no attribute 'afsk9600'

```

when I run into the ../build/swig directory, and run import module_swig  if happens I have the undefined symbols names ax25_init. 

```
wang@wang-VirtualBox:~/gnuradio-new-module$ cd gr-tutorial/
wang@wang-VirtualBox:~/gnuradio-new-module/gr-tutorial$ ls
apps  build  cmake  CMakeLists.txt  docs  examples  grc  include  lib  MANIFEST.md  python  swig
wang@wang-VirtualBox:~/gnuradio-new-module/gr-tutorial$ cd build/
wang@wang-VirtualBox:~/gnuradio-new-module/gr-tutorial/build$ cd swig/
wang@wang-VirtualBox:~/gnuradio-new-module/gr-tutorial/build/swig$ ls
CMakeFiles           tutorial_swig_doc_swig_docs    tutorial_swig.pyc             tutorial_swig_swig_2d0df.cpp     tutorial_swig.tag
cmake_install.cmake  _tutorial_swig_doc_tag         tutorial_swig.pyo             tutorial_swig_swig_2d0df.cpp.in
CTestTestfile.cmake  _tutorial_swig_doc_tag.cpp     tutorial_swigPYTHON_wrap.cxx  _tutorial_swig_swig_tag
Makefile             _tutorial_swig_doc_tag.cpp.in  _tutorial_swig.so             _tutorial_swig_swig_tag.cpp
tutorial_swig_doc.i  tutorial_swig.py               tutorial_swig_swig_2d0df      _tutorial_swig_swig_tag.cpp.in
wang@wang-VirtualBox:~/gnuradio-new-module/gr-tutorial/build/swig$ python2
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tutorial_swig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tutorial_swig.py", line 28, in <module>
    _tutorial_swig = swig_import_helper()
  File "tutorial_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_tutorial_swig', fp, pathname, description)
ImportError: /home/wang/gnuradio-new-module/gr-tutorial/build/lib/libgnuradio-tutorial-1.0.0git.so.0.0.0: undefined symbol: ax25_init
>>> 
```

I am wondering if you have the solutions.
Thank you!

Shiwang Xing,
Micro-satellites technology lab,
Beihang University

**Comment by bg2bhc** [comment]
你好，如果单纯的想改波特率不需要新建一个OOT，只需要把对应的输入输入采样率改成9600*8就可以，不过这样频偏也会跟着变。另外还请确认一下你想要的是什么调制方式，配合什么设备使用，据我了解成品设备没有用AFSK 9600的，带宽超标了。

**Comment by shiwang-Xing** [comment]
感谢提醒！最终的传输方式并不是AFSK，而是FSK9600。主要想使用OOT做新模块有两个方面的考虑。第一点是项目组目前购买的ISISpace应答机的上行协议已经改成了FSK9600 且需要加扰上行，所以想以韦老板的这个为出发点去深入学习GNURADIO。第二点是想通过学习可以了解更多的射频知识，本人现在在项目地面站工作了一年左右，现在对这方面很感兴趣，哈工大在这方面走在国内前列，希望可以了解更多相关知识。

**Comment by shiwang-Xing** [comment]
Hi, I figure this out. Because I forget to add the .c files into the cmake.txt which is in the ../lib direcotry

**Comment by warmonkey** [comment]
FSK modulation please use CPFSK module with a bitstream encoder.

shiwang-Xing <notifications@github.com> 于2019年12月19日周四 下午12:26写道：
