### ISSUE TITLE
vitfilt27_* is not accessible from python

### ISSUE THREAD

**Issue by thasti** [bg2bhc/gr-lilacsat#6]
After compiling and installing the current gr-lilacsat, I can not run the examples from GNU Radio companion. Running (for example) demod_by70_1.grc fails with:

 Traceback (most recent call last):
  File "/home/thasti/projekte/sat-trak/by70/gr-lilacsat/examples/demod_lilacsat1.py", line 462, in <module>
    main()
  File "/home/thasti/projekte/sat-trak/by70/gr-lilacsat/examples/demod_lilacsat1.py", line 450, in main
    tb = top_block_cls()
  File "/home/thasti/projekte/sat-trak/by70/gr-lilacsat/examples/demod_lilacsat1.py", line 293, in __init__
    self.lilacsat_vitfilt27_fb_0_0 = lilacsat.vitfilt27_fb()
AttributeError: 'module' object has no attribute 'vitfilt27_fb'

From Python console, I can import lilacsat, but instantiating a vitfilt27_fb fails as in the same way as it does in GNU Radio Companion. 

Any ideas on how to fix this?

**Comment by thasti** [comment]
I just noticed this error resulted from __init__.py catching the ImportError when failing to import lilacsat_swig silently and therefore without any notice that the library was not found, I now fixed the missing library path on my system.. sorry!

**Comment by bg2bhc** [comment]
Hi thasti, I found similar problem happen sometimes on Ubuntu 16.04 or new GNU Radio releases. Can you share me how you fix it? I am new to Linux. Thanks!

**Comment by thasti** [comment]
@bg2bhc I fixed it by adding the installation path of the gnuradio_lilacsat.so to the LD_LIBRARY_PATH using: 
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/ 
before starting GNU Radio Companion. I think this can also be overcome by setting the correct system library paths for cmake when building gr-lilacsat.

**Comment by warmonkey** [comment]
Have you tried sudo ldconfig after installation ?
Usually set LD_LIBRARY_PATH is unnecessary. /etc/ld.so.conf includes path /usr/local/lib
